# Generated by Django 4.0.5 on 2022-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
